### ISSUE TITLE
Springboard Crashing

### ISSUE THREAD

**Issue by n9than** [DGh0st/HSWidgets#10]
This tweak crashes and goes into safe mode after installing. I tried older versions and the only ones that work are 0.0.1 and 0.0.1-1. I attached a list of my tweaks if that helps at all.
[tweaks.txt](https://github.com/DGh0st/HSWidgets/files/5019839/tweaks.txt)

**Comment by DGh0st** [comment]
IconSupport is known to cause crashes on iOS 13 as it hasn't been updated.
