### ISSUE TITLE
[Feature Request] Option to hide name of app in today view widget

### ISSUE THREAD

**Issue by UInt2048** [DGh0st/HSWidgets#14]
I didn't take this picture, but the idea is to hide what's circled in it on the homescreen. The widgets have been added to it through HSWidgets. Could this be hidden on just the homescreen by an update to this tweak? If this is off-topic, I apologise.

<details>
<summary>Image</summary>

![image](https://user-images.githubusercontent.com/46784000/110136336-9058ac80-7d9d-11eb-81bc-940cc9abc0c4.jpeg)
</details>

**Comment by DGh0st** [comment]
HSWidgets is mostly responsible for providing the widgets on your homescreen, any UI customizations for those widgets would either be up to the widget or other UI customization tweaks. In this case I think there are a few tweaks that customization how today widgets look which should work with HSWidgets. Those tweaks probably change how it looks for both homescreen (today widgets using HSWidgets) and today page (today widgets on today page). If you want it to only change homescreen that would be a compatibility issue for that tweak.

I personally think that shouldn't be added to HSWidgets, however it is possible if someone wanted to though it would most likely conflict with almost all those UI customization tweaks.
