### ISSUE TITLE
IOS 14 support?

### ISSUE THREAD

**Issue by BluDood** [DGh0st/HSWidgets#15]
Can you add IOS 14 support? I know widgets are a thing, but I liked that it copied the lock screen clock so it looks similar.

**Comment by DGh0st** [comment]
HSWidgets is not going to be updated for iOS 14 due to the reason you mentioned. As to having a lockscreen clock widget, it would be easier to create a lockscreen clock widget using apple's new widget system than to re-create a widget system to then add the lockscreen widget on top of it.
