### ISSUE TITLE
Improve UI of widget selection to make it easier to understand how/why only some widgets can be added to the page

### ISSUE THREAD

**Issue by deadgarryboy** [DGh0st/HSWidgets#4]
how do i add widgets because all i’m getting is the placeholder one

**Comment by DGh0st** [comment]
The widgets shown in that menu are the ones that can currently be added on the page with the space available.
So more spaces available = more unique widgets that can be added to the page.

**Comment by DGh0st** [comment]
I am going to change this to improve UI to make it easier to understand how it works.

**Comment by DGh0st** [comment]
HSWidgets 0.1-1 should improve the UI
